<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="example">
  <xacro:macro name="gazebo_material" params="ref color">
    <gazebo reference="${ref}">
      <material>Gazebo/${color}</material>
    </gazebo>
  </xacro:macro>

  <xacro:include filename="$(find vehicle_simulator)/urdf/head.xacro" />

  <xacro:property name="PI" value="3.1415926"/>
  <!--parames-base-->
  <xacro:property name="base_box_x" value="0.6"/>
  <xacro:property name="base_box_y" value="0.4"/>
  <xacro:property name="base_box_z" value="0.3"/>
  <xacro:property name="base_mass" value="4"/>

  <!--parames-wheels-->
  <xacro:property name="wheel_radius" value="0.15"/>
  <xacro:property name="wheel_length" value="0.1"/>
  <xacro:property name="wheel_mass" value="0.2"/>
  
  <xacro:property name="wheel_offset_x" value="0.2"/>
  <xacro:property name="wheel_offset_y" value="0.25"/>
  <xacro:property name="wheel_offset_z" value="-0.1"/>

  
  <link name="base_origin"></link>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_box_x} ${base_box_y} ${base_box_z}"/>

      </geometry>
    </visual>

    <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <box size="${base_box_x} ${base_box_y} ${base_box_z}"/>

        </geometry>
     </collision>

    <xacro:Box_inertial_matrix m="${base_mass}" l="${base_box_x}" w="${base_box_y}" h="${base_box_z}"/>

  </link>

  <joint name="base_link_joint" type="fixed">
    <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
    <parent link="base_origin"/>
    <child link="base_link"/>
  </joint>

  <!--macro of wheel-->
   <xacro:macro name="add_wheel" params="name *joint_pose">
    <link name="${name}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${PI /2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${PI /2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertial_matrix m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}"/>
    </link>

    <joint name="${name}_joint" type="continuous">
      <xacro:insert_block name="joint_pose" />
      <parent link="base_link"/>
      <child link="${name}_wheel"/>
      <axis xyz="0 1 0" />
    </joint>

    <!-- f  link-->
    <gazebo reference="${name}_wheel">
      <selfCollide>false</selfCollide>
      <mu1>1.0</mu1>
      <mu2>0.5</mu2>
      <kp value="10000000.0" />
      <kd value="1.0" />
      <fdir1 value="1 0 0" />
    </gazebo>
    <transmission name="${name}_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${name}_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="${name}_actuator">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <xacro:property name="lfwheel_joint_x" value="${wheel_offset_x}"/>
  <xacro:property name="lfwheel_joint_y" value="${wheel_offset_y}"/>
  <xacro:property name="lfwheel_joint_r" value="0"/>

  <xacro:property name="lrwheel_joint_x" value="${-1 * wheel_offset_x}"/>
  <xacro:property name="lrwheel_joint_y" value="${wheel_offset_y}"/>
  <xacro:property name="lrwheel_joint_r" value="0"/>

  <xacro:property name="rfwheel_joint_x" value="${wheel_offset_x}"/>
  <xacro:property name="rfwheel_joint_y" value="${-1 * wheel_offset_y}"/>
  <xacro:property name="rfwheel_joint_r" value="0"/>

  <xacro:property name="rrwheel_joint_x" value="${-1 * wheel_offset_x}"/>
  <xacro:property name="rrwheel_joint_y" value="${-1 * wheel_offset_y}"/>
  <xacro:property name="rrwheel_joint_r" value="0"/>
  <!-- <xacro:property name="rrwheel_joint_r" value="${-1 * PI / 2}"/> -->



  <xacro:add_wheel name="left_front">
    <origin xyz="${lfwheel_joint_x} ${lfwheel_joint_y} ${wheel_offset_z}" rpy="${lfwheel_joint_r} 0 0"/>
  </xacro:add_wheel>

  <xacro:add_wheel name="left_rear">
    <origin xyz="${lrwheel_joint_x} ${lrwheel_joint_y} ${wheel_offset_z}" rpy="${lrwheel_joint_r} 0 0"/>
  </xacro:add_wheel>

  <xacro:add_wheel name="right_front">
    <origin xyz="${rfwheel_joint_x} ${rfwheel_joint_y} ${wheel_offset_z}" rpy="${rfwheel_joint_r} 0 0"/>
  </xacro:add_wheel>


  <xacro:add_wheel name="right_rear">
    <origin xyz="${rrwheel_joint_x} ${rrwheel_joint_y} ${wheel_offset_z}" rpy="${rrwheel_joint_r} 0 0"/>
  </xacro:add_wheel>


  <xacro:gazebo_material ref="base_link"         color="Red" />
  <xacro:gazebo_material ref="lidar_holder"      color="Black" />
  <xacro:gazebo_material ref="left_front_wheel"  color="Black" />
  <xacro:gazebo_material ref="left_rear_wheel"   color="Black" />
  <xacro:gazebo_material ref="right_front_wheel" color="Black" />
  <xacro:gazebo_material ref="right_rear_wheel"  color="Black" />

</robot>
